version: '3.8'

networks: 
  app:
  database:

services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=beach
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=beach
    volumes:
      - ./db/migrate:/docker-entrypoint-initdb.d
    networks: 
      - database
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: beach-api:1.0
    depends_on:
      - db
    networks: 
      - database
      - app
  frontend:
    image: nginx:1.23.2
    volumes:
      - ./ui:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
    networks: 
      - app